CREATE TABLE IF NOT EXISTS track_leads(
    lid INT NOT NULL REFERENCES users(uid) ON DELETE CASCADE,
    trackid INT NOT NULL REFERENCES track(tid) ON DELETE CASCADE,
    cohortid INT NOT NULL REFERENCES cohort(cid) ON DELETE CASCADE
)