CREATE TABLE IF NOT EXISTS quiz(
    qid SERIAL PRIMARY KEY NOT NULL,
    quiz VARCHAR(100) NOT NULL,
    created_at DATE NOT NULL DEFAULT CURRENT_DATE,
    quiz_degree INT NOT NULL,
    created_by INT NOT NULL DEFAULT 1 REFERENCES users(uid) ON DELETE SET DEFAULT
);